[package]
name = "ioracle"
version = "0.1.0"
authors = ["Denis K <orca84@protonmail.com>"]
edition = "2018"

[dependencies]
rocket = "0.4.5"
rppal = "0.11.3"
serde = "1.0.114"
serde_derive = "1.0.114"
uuid = { version = "0.8.1", features = ["v4"]  }

[dependencies.rocket_contrib]
version = "0.4.5"
default-features = false
features = ["tera_templates", "serve"]
