create table if not exists bindings (
    id integer not null primary key,
    file_name text not null,
    heaven_pin integer not null,
    heaven_colour text not null,
    cloud_pin integer not null,
    cloud_colour text not null,
    sun_pin integer not null,
    sun_colour text not null,
    wind_pin integer not null,
    wind_colour text not null,
    thunder_sound text not null,
    thunder_colour text not null,
    water_pin integer not null,
    water_colour text not null,
    mountain_sound text not null,
    mountain_colour text not null,
    earth_pin integer not null,
    earth_colour text not null,
    multiply text not null,
    bias text not null,
    threshold text not null
);

insert or ignore into bindings (
    id,
    file_name,
    heaven_pin,
    heaven_colour,
    cloud_pin,
    cloud_colour,
    sun_pin,
    sun_colour,
    wind_pin,
    wind_colour,
    thunder_sound,
    thunder_colour,
    water_pin,
    water_colour,
    mountain_sound,
    mountain_colour,
    earth_pin,
    earth_colour,
    multiply,
    bias,
    threshold
) values (
    1,
    "",
    0,
    "",
    0,
    "",
    0,
    "",
    0,
    "",
    "",
    "",
    0,
    "",
    "",
    "",
    0,
    "",
    "",
    "",
    ""
);
